### ISSUE TITLE
nao_bringup fails to launch naoqi_pose in kinetic

### ISSUE THREAD

**Issue by TGiles** [ros-naoqi/nao_robot#33]
When trying roslaunch nao_bringup nao_full.launch, the second part of the launch file which should start pose_controller and pose_manager fails. 

I have all the standard nao packages for kinetic installed, I have the correct python NaoQI sdk extracted and in the PYTHONPATH.
$ echo $PYTHONPATH
/home/tgiles/Desktop/CPSC495/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages::/home/tgiles/pynaoqi-python2.7-2.1.4.13-linux64

When attempting to launch the pose_manager by itself:
roslaunch naoqi_pose pose_manager.launch 
... logging to /home/tgiles/.ros/log/a7f89d3a-f301-11e6-8a39-64006a8872e3/roslaunch-dconner-5815.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dconner:40946/

SUMMARY
========

PARAMETERS
 * /pose_manager/poses/init/joint_names: ['Body']
 * /pose_manager/poses/init/positions: [0.0, 0.0, 1.39, ...
 * /pose_manager/poses/init/time_from_start: 1.5
 * /pose_manager/poses/zero/joint_names: ['Body']
 * /pose_manager/poses/zero/positions: [0.0, 0.0, 0.0, 0...
 * /pose_manager/poses/zero/time_from_start: 1.5
 * /pose_manager/xap: /opt/ros/kinetic/...
 * /rosdistro: kinetic
 * /rosversion: 1.12.6

NODES
  /
    pose_controller (naoqi_pose/pose_controller.py)
    pose_manager (naoqi_pose/pose_manager.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[pose_controller-1]: started with pid [5835]
process[pose_manager-2]: started with pid [5836]
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/naoqi_pose/pose_controller.py", line 49, in <module>
    from naoqi_driver.naoqi_node import NaoqiNode
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/naoqi_driver/__init__.py", line 29, in <module>
    from .naoqi_node import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/naoqi_driver/naoqi_node.py", line 37, in <module>
    raise RuntimeError("Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.")
RuntimeError: Error importing NaoQI. Please make sure that Aldebaran's NaoQI API is in your PYTHONPATH.
[pose_controller-1] process has died [pid 5835, exit code 1, cmd /opt/ros/kinetic/lib/naoqi_pose/pose_controller.py --pip=192.168.10.134 --pport=9559 __name:=pose_controller __log:=/home/tgiles/.ros/log/a7f89d3a-f301-11e6-8a39-64006a8872e3/pose_controller-1.log].
log file: /home/tgiles/.ros/log/a7f89d3a-f301-11e6-8a39-64006a8872e3/pose_controller-1*.log
[FATAL] [1487109991.554017]: Could not connect to required "joint_trajectory" action server, is the nao_controller node running?
[pose_manager-2] process has finished cleanly
log file: /home/tgiles/.ros/log/a7f89d3a-f301-11e6-8a39-64006a8872e3/pose_manager-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

I can find the script for pose_controller.py script in /opt/ros, but I can't seem to find the missing open source for naoqi_pose (since it looks like it was not maintained past jade), any advice?

**Comment by YuehChuan** [comment]
i got familar issue 
Nao model v3.2
HOST PC: ubuntu14.04.5
ROS indigo
python-2.7.6
GCC-4.8.4 
nao python C++ SDK 2.1.4.13

ROS package
sudo apt-get install ros-indigo-driver-base ros-indigo-move-base-msgs ros-indigo-octomap ros-indigo-octomap-msgs ros-indigo-humanoid-msgs ros-indigo-humanoid-nav-msgs ros-indigo-camera-info-manager ros-indigo-camera-info-manager-py

sudo apt-get install ros-indigo-nao-robot
sudo apt-get install ros-indigo-nao-meshes

pc ip 192.168.1.101
nao ip 192.168.1.100

roslaunch nao_bringup nao_full.launch nao_ip:=192.168.1.100 roscore_ip:=192.168.1.101
![nao_error](https://user-images.githubusercontent.com/7314531/30925468-865642f6-a3e4-11e7-90b0-0d4e4f52ba58.png)

```txt=
NODES
  /nao_robot/pose/
    pose_controller (naoqi_pose/pose_controller.py)
    pose_manager (naoqi_pose/pose_manager.py)
  /nao_robot/
    naoqi_driver (naoqi_driver/naoqi_driver_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[nao_robot/naoqi_driver-1]: started with pid [14886]
process[nao_robot/pose/pose_controller-2]: started with pid [14887]
process[nao_robot/pose/pose_manager-3]: started with pid [14888]
[INFO] [WallTime: 1506529716.178727] Connecting to NaoQi at 192.168.1.100:9559
[I] 14887 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[I] 14887 qimessaging.transportserver: TransportServer will listen on: tcp://192.168.1.101:34723
[I] 14887 qimessaging.transportserver: TransportServer will listen on: tcp://127.0.0.1:34723
[FATAL] [WallTime: 1506529719.182294] Could not connect to required "joint_trajectory" action server, is the nao_controller node running?
[nao_robot/pose/pose_manager-3] process has finished cleanly
log file: /home/schwarm/.ros/log/e6fe6b40-a3a0-11e7-9b4d-f0def191813b/nao_robot-pose-pose_manager-3*.log
[W] 14935 qi.eventloop: Error caught in eventloop(eventloop).async: Pointer Lock failed
[ERROR] [WallTime: 1506529721.184507] Could not create Proxy to "ALMotion". 
Exception message:
	ALBroker::createBroker
	Cannot connect to tcp://192.168.1.100:9559
[INFO] [WallTime: 1506529721.188671] Stopping pose_controller
[INFO] [WallTime: 1506529721.189192] pose_controller stopped
[nao_robot/pose/pose_controller-2] process has died [pid 14887, exit code 1, cmd /opt/ros/indigo/lib/naoqi_pose/pose_controller.py --pip=192.168.1.100 --pport=9559 __name:=pose_controller __log:=/home/schwarm/.ros/log/e6fe6b40-a3a0-11e7-9b4d-f0def191813b/nao_robot-pose-pose_controller-2.log].
log file: /home/schwarm/.ros/log/e6fe6b40-a3a0-11e7-9b4d-f0def191813b/nao_robot-pose-pose_controller-2*.log
^C[nao_robot/naoqi_driver-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

```

**Comment by ackranz** [comment]
me too. what did you do to get rid of it?

**Comment by CodingSaturn** [comment]
Hey, same situation as @YuehChuan here. 
Any news on what the solution is?

**Comment by hayday100** [comment]
I had the problem and it is due to my Linux network wireless interface name is not eth0, which is the default.  So I used the following complete command to fix it.

$ roslaunch nao_bringup nao_full.launch nao_ip:=... roscore_ip:=... network_interface:=...
